#!/usr/bin/env bash
# vendor-fonts.sh — Plan-8 W4 / Q-CSP-1 (self-host fonts).
# Fetches the 6 app font families from Google Fonts css2 (latin + latin-ext subsets
# only — the app is English/European), downloads the woff2 binaries into
# web/assets/fonts/, and (re)generates web/assets/css/fonts.css with local @font-face
# rules (src: url('/assets/fonts/...')). Re-run to refresh; do NOT hand-edit fonts.css.
#
# Requires network (curl). All six families are OFL/Apache — see web/assets/fonts/OFL.txt.
set -euo pipefail
cd "$(dirname "$0")/.."   # -> packages/pyeza-golang
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
CSS2="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700&family=Bricolage+Grotesque:wght@400;500;600;700;800&family=Figtree:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&family=Nunito:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap"
OUT="web/assets/fonts"; CSS="web/assets/css/fonts.css"
mkdir -p "$OUT" "$(dirname "$CSS")"
tmp="$(mktemp)"; curl -sS --max-time 30 -A "$UA" "$CSS2" -o "$tmp"
python3 - "$tmp" "$OUT" "$CSS" <<'PYEOF'
import re, sys
css=open(sys.argv[1]).read(); OUT=sys.argv[2]; CSSOUT=sys.argv[3]
KEEP={"latin","latin-ext"}
blocks=re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
rules=[]; dl=[]; seen=set()
for subset,block in blocks:
    if subset not in KEEP: continue
    fam=re.search(r"font-family:\s*'([^']+)'",block).group(1)
    wght=re.search(r"font-weight:\s*(\d+)",block).group(1)
    style=re.search(r"font-style:\s*(\w+)",block).group(1)
    url=re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)",block).group(1)
    ur=re.search(r"unicode-range:\s*([^;]+);",block).group(1).strip()
    slug=fam.lower().replace(" ","-"); ital="-italic" if style=="italic" else ""
    fn=f"{slug}-{wght}{ital}-{subset}.woff2"
    if fn in seen: continue
    seen.add(fn); dl.append(f"{url}\t{OUT}/{fn}")
    rules.append("@font-face {\n  font-family: '%s';\n  font-style: %s;\n  font-weight: %s;\n  font-display: swap;\n  src: url('/assets/fonts/%s') format('woff2');\n  unicode-range: %s;\n}"%(fam,style,wght,fn,ur))
open("/tmp/_dl.txt","w").write("\n".join(dl)+"\n")
hdr="/* Self-hosted fonts (Plan-8 W4 / Q-CSP-1). Generated by scripts/vendor-fonts.sh from\n   Google Fonts css2 (latin + latin-ext subsets). 6 families, OFL/Apache. Re-run to refresh; do NOT hand-edit. */\n\n"
open(CSSOUT,"w").write(hdr+"\n\n".join(rules)+"\n")
print(f"{len(rules)} @font-face rules")
PYEOF
while IFS=$'\t' read -r url dest; do [ -n "$url" ] && curl -sS --max-time 30 -A "$UA" "$url" -o "$dest"; done < /tmp/_dl.txt
echo "vendored $(ls "$OUT"/*.woff2 2>/dev/null | wc -l | tr -d ' ') woff2 into $OUT; regenerated $CSS"
